[build-system]
requires = [
    "setuptools>=43",
    "wheel"
]
build-backend = "setuptools.build_meta"

[[tool.mypy.overrides]]
module = [
    "lxml",
    "graphviz",
    "pkommand"
]
ignore_missing_imports = true