name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pipenv"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
      - name: Install lib
        run: |
          pipenv requirements --dev > requirements_dev.txt
          python -m pip install -r requirements_dev.txt
      - name: Lint
        run: tox -e black,isort,flake8,mypy,pydocstyle -p 4
      - name: Test
        run: tox -e py310
